### ISSUE TITLE
[FEAT] 리스트페이지_UI구현

### ISSUE THREAD

**Issue by ChoSeunghyeon** [2022OSS-Dev-Competition-ENG-Project/ENG_Web#14]
## 📌  Feature Issue
리스트페이지 UI 구현

## 📝  To-do

- [x] 건물 리스트 페이지
- [x] 공지사항 리스트 페이지
- [x] 게시물 리스트 페이지
- [x] 신고현황 리스트 페이지

**Comment by ChoSeunghyeon** [comment]
리스트 페이지 UI 구현 완료
