### ISSUE TITLE
[FEAT] 메인페이지_UI구현

### ISSUE THREAD

**Issue by ChoSeunghyeon** [2022OSS-Dev-Competition-ENG-Project/ENG_Web#7]
## 📌  Feature Issue
로그인 후 메인 페이지 UI구현

## 📝  To-do

- [x] Header Component 구현
- [x] Navigation Componet 구현
- [x] Footer Componet 구현
- [x] 레이아웃 Component 구현

**Comment by ChoSeunghyeon** [comment]
UI구현 완료
